const path = require("node:path");
const { spawnSync } = require("node:child_process");

const tests = [
  "self_check.js",
  "windows_installer_smoke.js",
  "cross_machine_runtime_smoke.js",
  "startup_scripts_smoke.js",
  "background_process_visibility_smoke.js",
  "scoring_url_smoke.js",
  "job_eligibility_smoke.js",
  "browser_transport_smoke.js",
  "browser_supervisor_smoke.js",
  "portable_edge_runtime_smoke.js",
  "runtime_paths_smoke.js",
  "browser_readiness_smoke.js",
  "workspace_tabs_smoke.js",
  "scan_execution_smoke.js",
  "scan_store_contract_smoke.js",
  "site_access_budget_smoke.js",
  "boss_safe_pacing_smoke.js",
  "site_access_usage_smoke.js",
  "workflow_planner_smoke.js",
  "workflow_acquisition_smoke.js",
  "inherited_search_scope_smoke.js",
  "scoped_keyword_stats_smoke.js",
  "scan_snapshot_smoke.js",
  "scan_recovery_smoke.js",
  "batch_state_consistency_smoke.js",
  "scan_cli_lifecycle_smoke.js",
  "workflow_scan_smoke.js",
  "workflow_scan_analysis_smoke.js",
  "scan_end_to_end_recovery_smoke.js",
  "storage_migration_smoke.js",
  "gate_d_baseline_smoke.js",
  "gate_d_evaluation_export_smoke.js",
  "communication_store_contract_smoke.js",
  "candidate_store_contract_smoke.js",
  "message_learning_store_smoke.js",
  "message_reply_send_store_smoke.js",
  "message_reply_send_service_smoke.js",
  "message_reply_send_executor_smoke.js",
  "boss_message_reply_sender_smoke.js",
  "dashboard_message_reply_send_smoke.js",
  "message_reply_learning_smoke.js",
  "job_store_contract_smoke.js",
  "workflow_store_contract_smoke.js",
  "candidate_progress_storage_smoke.js",
  "funnel_threshold_policy_smoke.js",
  "funnel_strategy_round_store_smoke.js",
  "job_search_funnel_smoke.js",
  "funnel_message_observation_smoke.js",
  "funnel_diagnosis_smoke.js",
  "message_follow_up_smoke.js",
  "message_follow_up_service_smoke.js",
  "dashboard_message_follow_up_controller_smoke.js",
  "matching_card_smoke.js",
  "workflow_storage_smoke.js",
  "workflow_control_smoke.js",
  "workflow_task_storage_smoke.js",
  "workflow_progress_smoke.js",
  "workflow_analysis_executor_smoke.js",
  "workflow_inventory_smoke.js",
  "workflow_health_smoke.js",
  "workflow_communication_smoke.js",
  "communication_cli_authority_smoke.js",
  "dashboard_runtime_smoke.js",
  "dashboard_information_architecture_smoke.js",
  "dashboard_shell_smoke.js",
  "dashboard_funnel_smoke.js",
  "dashboard_wave2_acceptance_smoke.js",
  "today_dashboard_smoke.js",
  "dashboard_asset_failure_smoke.js",
  "workflow_dashboard_smoke.js",
  "workflow_application_smoke.js",
  "analysis_application_smoke.js",
  "communication_runtime_smoke.js",
  "communication_application_smoke.js",
  "workflow_page_migration_smoke.js",
  "workflow_recovery_smoke.js",
  "workflow_end_to_end_smoke.js",
  "communication_batch_storage_smoke.js",
  "communication_executor_smoke.js",
  "dashboard_communication_batch_smoke.js",
  "communication_calibration_gate_smoke.js",
  "dashboard_scan_lifecycle_smoke.js",
  "model_adapter_smoke.js",
  "model_parser_resilience_smoke.js",
  "resume_parser_pdf_order_smoke.js",
  "resume_privacy_smoke.js",
  "resume_optimization_contract_smoke.js",
  "resume_optimization_store_smoke.js",
  "resume_optimization_service_smoke.js",
  "dashboard_resume_optimization_smoke.js",
  "mock_interview_contract_smoke.js",
  "mock_interview_store_smoke.js",
  "mock_interview_service_smoke.js",
  "dashboard_mock_interview_smoke.js",
  "analyzer_initialization_smoke.js",
  "model_settings_smoke.js",
  "cli_model_settings_root_smoke.js",
  "model_task_profiles_smoke.js",
  "model_settings_ui_smoke.js",
  "onboarding_run_smoke.js",
  "initial_search_page_smoke.js",
  "onboarding_progress_ui_smoke.js",
  "onboarding_cli_smoke.js",
  "observability_smoke.js",
  "observability_context_smoke.js",
  "profile_quality_smoke.js",
  "search_plan_modes_smoke.js",
  "semantic_pipeline_smoke.js",
  "shadow_scorecard_smoke.js",
  "scalar_shadow_scorecard_smoke.js",
  "four_tier_pipeline_smoke.js",
  "outcome_analytics_smoke.js",
  "four_tier_product_surface_smoke.js",
  "outcome_analytics_dashboard_smoke.js",
  "four_tier_benchmark_metrics_smoke.js",
  "generic_evidence_matching_smoke.js",
  "source_acquisition_smoke.js",
  "boss_communication_page_smoke.js",
  "boss_message_dom_smoke.js",
  "boss_message_reader_smoke.js",
  "boss_message_detail_reader_smoke.js",
  "message_discovery_job_context_smoke.js",
  "message_preview_state_smoke.js",
  "message_discovery_smoke.js",
  "message_reply_contract_smoke.js",
  "dashboard_message_discovery_smoke.js",
  "dashboard_communication_profile_smoke.js",
  "activity_status_smoke.js",
  "data_visibility_smoke.js",
  "screening_quality_smoke.js",
  "onboarding_smoke.js",
  "communication_smoke.js",
  "flow_smoke.js",
  "job_match_benchmark.js",
  "private_full_chain_runner_smoke.js"
];

const timeoutByTest = {
  "windows_installer_smoke.js": 180_000,
  "startup_scripts_smoke.js": 240_000,
  "model_task_profiles_smoke.js": 180_000
};

for (const file of tests) {
  console.log(`\n> ${file}`);
  const result = spawnSync(process.execPath, [path.join(__dirname, file)], {
    cwd: path.join(__dirname, ".."),
    stdio: "inherit",
    timeout: timeoutByTest[file] || 120_000
  });
  if (result.error) {
    console.error(`${file}: ${result.error.message}`);
    process.exit(1);
  }
  if (result.status !== 0) process.exit(result.status || 1);
}

console.log(`\nAll ${tests.length} offline checks passed.`);
