"use strict";

const { escapeHtml, escapeAttr } = require("../http/response");
const { renderDashboardFrame } = require("../ui/shell");
const { renderWorkflowHealthPanel } = require("../workflow_health_view");

function renderWorkflowPage(vm = {}) {
  const page = vm.page || {};
  return renderDashboardFrame({ currentPath: page.currentPath, todayPath: page.planHref, planId: page.planId, stage: "本轮执行", brandHref: page.planHref, content: `<main id="main-content" class="workflow-shell" data-workflow-page data-polling-kind="${escapeAttr(vm.polling?.kind || "none")}" data-workflow-run-id="${escapeAttr(vm.polling?.runId || page.runId)}" data-polling-interval="${Number(vm.polling?.intervalMs || 2500)}" data-polling-key="${escapeAttr(vm.polling?.initialKey || "")}" data-terminal-states="${escapeAttr((vm.polling?.terminalStates || []).join(","))}">
  ${renderHeader(vm)}${renderPrimaryCommand(vm.phase, vm.controls)}${renderPhase(vm.phase)}${renderScope(vm.scope)}${vm.health?.report?.status ? renderWorkflowHealthPanel(vm.health.report) : ""}${renderProgress(vm.progress)}
</main><script src="/assets/workflow.js"></script>` });
}

function renderHeader(vm) {
  const header = vm.header || {};
  const page = vm.page || {};
  return `<header class="workflow-head"><div class="workflow-headline"><div><p class="workflow-sequence">第 ${number(header.sequence)} 轮 · ${escapeHtml(header.localDay)}</p><h1>${escapeHtml(header.statusLabel)}</h1></div><a href="${escapeAttr(page.planHref)}">返回筛选方案</a></div><div class="workflow-progress"><span>本轮目标 <strong>${number(header.targetSuccessCount)}</strong></span><span>本轮成功 <strong>${number(header.successfulCount)}</strong></span><span>今日进度 <strong>${number(header.todaySuccessful)} / ${number(header.dailyTarget)}</strong></span><span>有效候选 <strong>${number(header.inventoryCount)}</strong></span></div></header>`;
}

function renderScope(scope = {}) {
  if (!scope.visible) return "";
  return `<section class="workflow-scope"><strong>筛选来源：BOSS 当前页面</strong><ul>${(scope.filters || []).map((item) => `<li>${escapeHtml(item)}</li>`).join("") || "<li>使用平台默认筛选</li>"}</ul><p>范围：${escapeHtml(scope.scopeKey)} · 关键词来源：Search Plan #${escapeHtml(scope.sourcePlanId)}</p><p>本轮关键词：${escapeHtml((scope.keywords || []).join("、") || "无")}</p>${scope.unresolved?.length ? `<p class="workflow-alert">未解析平台筛选：${escapeHtml(scope.unresolved.join("、"))}；采集 URL 已保留这些条件，本地不会猜值。</p>` : ""}<p class="hint">修改 BOSS 筛选会创建新的统计范围；本轮恢复仍使用当前冻结范围。</p></section>`;
}

function renderPrimaryCommand(phase = {}, controls = {}) {
  if (phase.kind !== "active" || (!controls.runningVisible && !controls.pausedVisible)) return "";
  const stop = controls.stopPreview || {};
  const access = stop.access || {};
  const identity = `<input type="hidden" name="workflowRunId" value="${escapeAttr(controls.runId)}">`;
  const runningPrimary = controls.runningVisible ? ' data-workflow-primary="true"' : "";
  const pausedPrimary = controls.pausedVisible ? ' data-workflow-primary="true"' : "";
  return `<section class="workflow-command" aria-label="本轮操作"><div class="workflow-control-area"><div class="workflow-control-group" data-control-group="running"${controls.runningVisible ? "" : " hidden"}><form method="post" action="${escapeAttr(controls.endpoint)}" data-workflow-control-form>${identity}<input type="hidden" name="action" value="pause"><button${runningPrimary} data-workflow-control data-action="pause"${controls.canPause ? "" : " disabled"}>暂停本轮</button></form><button class="workflow-stop" type="button" data-workflow-control data-action="stop-preview"${controls.canStop ? "" : " disabled"}>结束本轮…</button></div><div class="workflow-control-group" data-control-group="paused"${controls.pausedVisible ? "" : " hidden"}><form method="post" action="${escapeAttr(controls.endpoint)}" data-workflow-control-form>${identity}<input type="hidden" name="action" value="resume"><button${pausedPrimary} data-workflow-control data-action="resume"${controls.canResume ? "" : " disabled"}>继续本轮</button></form><button class="workflow-stop" type="button" data-workflow-control data-action="stop-preview"${controls.canStop ? "" : " disabled"}>结束本轮…</button><strong>本轮已暂停</strong><span data-pause-reason>${escapeHtml(controls.pauseReason)}</span><a class="button-link" href="/settings#model-profile-batch_screening">测试批量模型连接</a><a class="button-link" href="/settings#model-profile-batch_screening">调整批量模型</a></div><section class="workflow-stop-confirmation" data-stop-confirmation hidden><h3>确认结束本轮</h3><p>已采集 <span data-stop-collected>${number(stop.collected)}</span> · 已分析 <span data-stop-analyzed>${number(stop.analyzed)}</span> · 失败 <span data-stop-failed>${number(stop.failed)}</span> · 未完成 <span data-stop-unfinished>${number(stop.unfinished)}</span></p><p>网页预算：详情 ${number(access.details)} · 页面 ${number(access.pages)} · 滚动 ${number(access.scrolls)}</p><p><strong data-stop-slot>${stop.consumesRunSlot ? "会占用今天一轮" : "不会占用今天一轮"}</strong>。结束后不能继续，已保存结果会保留。</p><div class="workflow-control-group"><form method="post" action="${escapeAttr(controls.endpoint)}" data-workflow-control-form>${identity}<input type="hidden" name="action" value="stop"><input type="hidden" name="confirmStop" value="1"><button class="workflow-stop" data-workflow-control data-action="stop-confirm">确认结束本轮</button></form><button type="button" data-action="stop-cancel">取消</button></div></section></div></section>`;
}

function renderProgress(progress) {
  if (!progress?.visible) return "";
  const analysis = progress.analysis || {};
  return `<section class="workflow-live" data-workflow-panel data-progress-revision="${number(progress.revision)}"><div class="workflow-live-head"><div aria-live="polite"><p class="workflow-stage" data-stage-label>第 ${number(progress.stageIndex)} 阶段 / 共 ${number(progress.stageCount)} 阶段</p><h2 data-stage-name>${escapeHtml(progress.stage)}</h2></div><p class="workflow-model">${escapeHtml(progress.modelLabel)}</p></div><progress class="workflow-meter" data-analysis-progress aria-label="岗位分析完成进度" max="${number(progress.meter?.max) || 1}" value="${number(progress.meter?.value)}"></progress><div class="workflow-analysis-grid" aria-label="岗位分析数量">${stat("总数", analysis.total, "data-analysis-total")}${stat("成功", analysis.succeeded, "data-analysis-succeeded")}${stat("处理中", analysis.running, "data-analysis-running")}${stat("等待重试", analysis.retryPending, "data-analysis-retry-pending")}${stat("待补详情", analysis.detailRequired, "data-analysis-detail-required")}${stat("已读详情", analysis.detailsRead, "data-detail-read")}${stat("待读详情", analysis.detailsPending, "data-detail-pending")}${stat("失败", analysis.failed, "data-analysis-failed")}${stat("剩余", analysis.remaining, "data-analysis-remaining")}</div><div class="workflow-live-meta"><section class="workflow-live-card"><h3>超时保护</h3><p data-analysis-timeouts>当前恢复周期最终超时 ${number(analysis.circuitTimeoutJobs)} / ${number(analysis.timeoutPauseThreshold)} · 本轮累计超时 ${number(analysis.lifetimeTimeoutJobs)}</p><p data-eta>${escapeHtml(progress.etaLabel)}</p></section><section class="workflow-live-card"><h3>最近活动</h3><p data-recent-activity aria-live="polite">${escapeHtml(progress.recentActivityLabel)}</p></section></div><p class="workflow-scan-wait" data-scan-wait${progress.scanWaitLabel ? "" : " hidden"}>${escapeHtml(progress.scanWaitLabel)}</p><p class="workflow-stale" data-workflow-stale hidden>任务可能失去活动，请先检查诊断信息，不要重复启动。</p><p class="workflow-inline-error" data-workflow-error role="alert" hidden>无法读取任务状态</p></section>`;
}

function renderPhase(phase = {}) {
  if (phase.kind === "review") return renderReview(phase);
  if (phase.kind === "confirmed") return renderConfirmed(phase);
  if (phase.kind === "communicating") return renderCommunicating(phase);
  if (phase.kind === "completed") return `<section class="workflow-phase"><div class="workflow-done"><h2>本轮已完成</h2><p>本轮成功 ${number(phase.successfulCount)}，今日进度 ${number(phase.todaySuccessful)} / ${number(phase.dailyTarget)}。</p>${phase.shortfall ? `<p class="hint">${escapeHtml(phase.shortfall)}</p>` : ""}</div><div class="workflow-actions"><a class="button-link" data-workflow-primary="true" href="${escapeAttr(phase.planHref)}">返回今日任务</a><a class="button-link" href="${escapeAttr(phase.queueHref)}">查看岗位记录</a></div></section>`;
  if (phase.kind === "interrupted") return `<section class="workflow-phase"><div class="workflow-actions">${phase.communicationHref ? `<a class="button-link" data-workflow-primary="true" href="${escapeAttr(phase.communicationHref)}">检查沟通中断项</a>` : renderResume(phase.resume)}</div><div class="workflow-alert"><strong>本轮已中断</strong><p>${escapeHtml(phase.errorCode)} · ${escapeHtml(phase.errorMessage)}</p></div></section>`;
  if (phase.kind === "active") return "";
  return `<section class="workflow-phase"><div class="workflow-alert"><strong>本轮状态已结束</strong><p>${escapeHtml(phase.errorCode)}</p></div><div class="workflow-actions"><a class="button-link" data-workflow-primary="true" href="${escapeAttr(phase.planHref)}">返回今日任务</a></div></section>`;
}

function renderReview(phase) {
  const review = phase.review || {};
  const rows = (review.rows || []).map((job) => `<label class="workflow-job"><input type="checkbox" name="jobIds" value="${escapeAttr(job.id)}"${job.defaultChecked ? " checked" : ""}><span class="workflow-job-main"><strong>${job.url ? `<a href="${escapeAttr(job.url)}" target="_blank" rel="noreferrer">${escapeHtml(job.title)}</a>` : escapeHtml(job.title)}</strong><span class="workflow-job-meta">${escapeHtml(job.company)} · ${escapeHtml(job.salary)} · ${escapeHtml(job.experience)} · ${escapeHtml(job.schedule)}</span><span class="workflow-job-evidence">${escapeHtml(job.evidence)}</span><span class="workflow-job-reason">${escapeHtml(job.reason)}</span>${job.hardBlockers?.length ? `<span class="workflow-job-reason">硬性限制：${escapeHtml(job.hardBlockers.join("；"))}</span>` : ""}</span><span class="workflow-tier">${escapeHtml(job.tier)}</span></label>`).join("") || "<p class=\"hint\">本轮没有满足有效期、详情和匹配证据要求的候选。</p>";
  const summary = `<p class="hint">本轮成功目标 ${number(phase.targetSuccessCount)}；主投和可投默认勾选 ${number(review.defaultCount)} 个，包含补位项。慎投仅展示，需人工决定是否勾选。</p>`;
  const runtimeBlock = review.runtimeBlock ? `<div class="workflow-alert">${escapeHtml(review.runtimeBlock.reasonCode)}${review.runtimeBlock.blockedUntil ? ` · ${escapeHtml(review.runtimeBlock.blockedUntil)}` : ""}</div>` : "";
  return `<section class="workflow-phase"><h2>确认本轮沟通清单</h2><form id="workflow-review-form" method="post" action="/api/communication-batch" data-review-limit="${number(review.quotaRemaining)}" data-review-blocked="${review.runtimeBlock ? "true" : "false"}"><input type="hidden" name="workflowRunId" value="${escapeAttr(phase.runId || "")}"><input type="hidden" name="planId" value="${escapeAttr(phase.planId || "")}"><input type="hidden" name="browserMode" value="${escapeAttr(review.browserMode)}"><div class="workflow-sticky"><span>已选 <output id="workflow-selected-count">${number(review.defaultCount)}</output> 个 · 今日剩余额度 ${number(review.quotaRemaining)}</span><button data-workflow-primary="true" id="workflow-confirm"${review.blocked ? " disabled" : ""}>确认清单</button></div>${summary}${runtimeBlock}<div class="workflow-list">${rows}</div></form></section>`;
}

function renderConfirmed(phase) { const communication = phase.communication || {}; return `<section class="workflow-phase"><h2>清单已确认</h2><p>已选择 ${number(communication.summary?.total)} 个岗位，本轮成功目标 ${number(phase.targetSuccessCount)}。</p>${communication.runtimeBlock ? `<div class="workflow-alert">${escapeHtml(communication.runtimeBlock)}</div>` : ""}<div class="workflow-actions">${communication.executionEnabled ? `<form method="post" action="/api/communication-control"><input type="hidden" name="batchId" value="${escapeAttr(communication.batchId)}"><button data-workflow-primary="true" name="action" value="${escapeAttr(communication.action)}">${escapeHtml(communication.actionLabel)}</button></form>` : ""}<a class="button-link"${communication.executionEnabled ? "" : ' data-workflow-primary="true"'} href="${escapeAttr(communication.detailsHref)}">${escapeHtml(communication.detailsLabel || "检查清单详情")}</a></div></section>`; }
function renderCommunicating(phase) { const communication = phase.communication || {}; const rows = Object.entries(communication.summary?.statusCounts || {}).map(([status, count]) => `<tr><th>${escapeHtml(status)}</th><td>${number(count)}</td></tr>`).join(""); return `<section class="workflow-phase"><h2>正在沟通</h2>${communication.runtimeBlock ? `<div class="workflow-alert">${escapeHtml(communication.runtimeBlock)}</div>` : ""}<table class="workflow-status-table"><tbody>${rows}</tbody></table><div class="workflow-actions"><a class="button-link" data-workflow-primary="true" href="${escapeAttr(communication.detailsHref)}">查看执行明细</a></div></section>`; }
function renderResume(resume) { if (!resume) return ""; const identity = `<input type="hidden" name="workflowRunId" value="${escapeAttr(resume.runId)}">`; if (resume.inherited) return `<form method="post" action="${escapeAttr(resume.endpoint)}">${identity}${resume.cdpPort ? `<input type="hidden" name="cdpPort" value="${number(resume.cdpPort)}">` : ""}<input type="hidden" name="browserMode" value="${escapeAttr(resume.browserMode)}"><span class="hint">${resume.browserMode === "portable" ? "使用项目专用 Edge 的 BOSS 搜索页" : "使用当前已登录 Edge 中的固定 BOSS 搜索页"}</span><button data-workflow-primary="true">继续本轮</button></form>`; return `<form method="post" action="${escapeAttr(resume.endpoint)}">${identity}<select name="browserMode"><option value="edge"${resume.browserMode === "edge" ? " selected" : ""}>当前已登录 Edge</option><option value="portable"${resume.browserMode === "portable" ? " selected" : ""}>项目专用 Edge</option></select><button data-workflow-primary="true">继续本轮</button></form>`; }
function stat(label, value, hook) { return `<div class="workflow-stat"><span>${escapeHtml(label)}</span><strong ${hook}>${number(value)}</strong></div>`; }
function number(value) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }

module.exports = { renderWorkflowPage };
